name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Package JAR
        run: sbt assembly
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/bf-compiler.jar"
          artifactContentType: "application/java-archive"
          artifactErrorsFailBuild: "true"